name: canvas_of_the_heart
description: "Canvas of the Heart — an interactive story about Emi Akimoto."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/title.png
    - assets/images/hallwayy.png
    - assets/images/door.png
    - assets/images/art_room.png
    - assets/images/passion.jpg
    - assets/images/passed.jpg
    - assets/images/hidden.png
    - assets/images/critique.jpg
    - assets/images/ending_good.jpg
    - assets/images/ending_neutral.png
    - assets/images/ending_bad.png
    - assets/sounds/bgmusic.mp3
    - assets/sounds/click.mp3
    - assets/sounds/good_ending.mp3
    - assets/sounds/neutral_ending.mp3
    - assets/sounds/ending_bad.mp3
